/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TASKBAG_H_RPCGEN
#define _TASKBAG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Task {
	int id;
	char *type;
	char *descr;
	int done;
};
typedef struct Task Task;

#define TaskBagService 1337
#define ONE 1

#if defined(__STDC__) || defined(__cplusplus)
#define putTask 1
extern  char ** puttask_1(Task *, CLIENT *);
extern  char ** puttask_1_svc(Task *, struct svc_req *);
#define getTask 2
extern  char ** gettask_1(char **, CLIENT *);
extern  char ** gettask_1_svc(char **, struct svc_req *);
#define readTask 3
extern  char ** readtask_1(char **, CLIENT *);
extern  char ** readtask_1_svc(char **, struct svc_req *);
extern int taskbagservice_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define putTask 1
extern  char ** puttask_1();
extern  char ** puttask_1_svc();
#define getTask 2
extern  char ** gettask_1();
extern  char ** gettask_1_svc();
#define readTask 3
extern  char ** readtask_1();
extern  char ** readtask_1_svc();
extern int taskbagservice_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Task (XDR *, Task*);

#else /* K&R C */
extern bool_t xdr_Task ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TASKBAG_H_RPCGEN */
