/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "taskbag.h"
#include <iostream>
#include <vector>
#include <string>

using namespace std;

static vector<Task*> taskbag;
<<<<<<< HEAD
=======

>>>>>>> 5b4f1effda13306e4059a1a1394effe8b898daca

char **
puttask_1_svc(Task *argp, struct svc_req *rqstp)
{
	static char * result = "puttask_1_svc";
	
	/*
	 * insert server code here
	 */
	Task *tmp = new Task;
	tmp->id = taskbag.size();
	tmp->descr = new char[strlen(argp->descr)];
	strcpy(tmp->descr,argp->descr);
	tmp->type = new char[strlen(argp->type)];
	strcpy(tmp->type, argp->type);
	tmp->done = 0;
	
	cout << "Put: " << endl;
	cout << "ID = " << tmp->id << endl;
	printf("Type =  %s \n", argp->type);
	printf("Description =  %s \n", argp->descr);
	
	taskbag.push_back(tmp);
	
<<<<<<< HEAD
=======

>>>>>>> 5b4f1effda13306e4059a1a1394effe8b898daca
	return &result;
}

int find(vector<Task*> bag, char *type){
<<<<<<< HEAD
  for(int i = 0; i < bag.size(); i++){
    if((!strcmp(bag[i]->type, type)))
      if(bag[i]->done == 0)
	return i;
=======
  printf("Search =  %s \n", type);
  for(int i = 0; i < bag.size(); i++){
    printf("Have = %s\n", bag[i]->type);
    if((!strcmp(bag[i]->type, type)))
      if(bag[i]->done == 0){
	cout << i << endl;
	return i;
      }
>>>>>>> 5b4f1effda13306e4059a1a1394effe8b898daca
  }
  return -1;
}

char **
gettask_1_svc(char **argp, struct svc_req *rqstp)
{
<<<<<<< HEAD
	static char * result;
	result = (char *) NULL;
=======
	static char * result  = (char *) NULL;
	printf("result =  %s \n", *argp);
>>>>>>> 5b4f1effda13306e4059a1a1394effe8b898daca
	/*
	 * insert server code here
	 */
	int place = find(taskbag, *argp);
	if(place != -1){
	  result = taskbag[place]->descr;
	  taskbag[place]->done = 1;
<<<<<<< HEAD
	  
=======
>>>>>>> 5b4f1effda13306e4059a1a1394effe8b898daca
	}
	return &result;
}

char **
readtask_1_svc(char **argp, struct svc_req *rqstp)
{
<<<<<<< HEAD
	static char * result;
	result = (char *) NULL;
=======
	static char * result = (char *) NULL;
>>>>>>> 5b4f1effda13306e4059a1a1394effe8b898daca
	//printf("result =  %s \n", *argp);

	/*
	 * insert server code here
	 */
	int place = find(taskbag, *argp);
	if(place != -1)
<<<<<<< HEAD
	  result = (taskbag[place]->descr);	
=======
	  result = (taskbag[place]->descr);
	else
	  result = "Not Found!";	
>>>>>>> 5b4f1effda13306e4059a1a1394effe8b898daca
	
	return &result;
}
