/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "taskbag.h"

bool_t
xdr_Task (XDR *xdrs, Task *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->type, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->descr, 50))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->done))
		 return FALSE;
	return TRUE;
}
