/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "taskbag.h"
#include <iostream>
#include <string>

using namespace std;

void
taskbagservice_1(char *host, char *argv[])
{
	std::cout << "Start" << std::endl;
	CLIENT *clnt;
	char * *result_1;
	Task  puttask_1_arg;
	char * *result_2 = (char **) NULL;
	char * gettask_1_arg = argv[3];
	char * *result_3  = (char **) NULL;
	char * readtask_1_arg = argv[3];

#ifndef	DEBUG
	clnt = clnt_create (host, TaskBagService, ONE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	char * requ = argv[2];
	if(!strcmp(requ, "put")){
	  puttask_1_arg.type = argv[3];
	  puttask_1_arg.descr = argv[4];
	  result_1 = puttask_1(&puttask_1_arg, clnt);
	  if (result_1 == (char **) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
	}
	
	if(!strcmp(requ, "get")){
	  while(result_2 == (char **) NULL)
	    result_2 = gettask_1(&gettask_1_arg, clnt);
	  
	  printf("Result =  %s \n", *result_2);
	}
	
	if(!strcmp(requ, "read")){
	  while(result_3 == (char **) NULL)
	    result_3 = readtask_1(&readtask_1_arg, clnt);
	  
	  printf("Result =  %s \n", *result_3);
	}
	
	//printf("result =  %s \n", *result_1);
	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host, put|get|read, \"übergabe\"\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	taskbagservice_1 (host, argv);
exit (0);
}
