/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "taskbag.h"

bool_t
xdr_echo_struct (XDR *xdrs, echo_struct *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->p1, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->p2, 50))
		 return FALSE;
	return TRUE;
}
