/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TASKBAG_H_RPCGEN
#define _TASKBAG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct echo_struct {
	char *p1;
	char *p2;
};
typedef struct echo_struct echo_struct;

#define ECHO_TEST 1234567
#define ONE 1

#if defined(__STDC__) || defined(__cplusplus)
#define ECHO 1
extern  char ** echo_1(echo_struct *, CLIENT *);
extern  char ** echo_1_svc(echo_struct *, struct svc_req *);
extern int echo_test_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ECHO 1
extern  char ** echo_1();
extern  char ** echo_1_svc();
extern int echo_test_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_echo_struct (XDR *, echo_struct*);

#else /* K&R C */
extern bool_t xdr_echo_struct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TASKBAG_H_RPCGEN */
