/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "taskbag.h"

char **
echo_1_svc(echo_struct *argp, struct svc_req *rqstp)
{
	static char * result;
	
	result = argp->p1;
	
	/*
	 * insert server code here
	 */

	return &result;
}
