/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "taskbag.h"


void
echo_test_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	echo_struct  echo_1_arg;
	
	echo_1_arg.p1 = argv[2];
	echo_1_arg.p2 = "test2";
#ifndef	DEBUG
	clnt = clnt_create (host, ECHO_TEST, ONE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = echo_1(&echo_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("result =  %s \n", *result_1);	//Ausgabe des Empfangenen
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	echo_test_1 (host);
	
exit (0);
}
